config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :sites do
    resources :notes
  end
  resources :plans
  resources :organisations

  root 'sites#index'
  get 'about' => 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :site
  validates :body, presence: true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :sites
  validates :name, presence: true, length: { minimum: 2}
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :sites
  validates :name, presence: true
end

app/models/site.rb
class Site < ApplicationRecord

  validates :url, presence: true

  belongs_to :organisation
  belongs_to :plan
  has_many :notes, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? }}

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    where("url ILIKE ?", "%#{search}%")
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :site
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  def  sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def show
    @note = Note.find(params[:id])
  end

  def create
    @site = Site.find(params[:site_id])
    @note = @site.notes.create(note_params)

    if @note.save
      redirect_to site_path(@site)
    else
      flash[:Error] = "Please complete all fields"
    end
  end

  def edit
    @site = Site.find(params[:site_id])
    @note = @site.note.find(note_params)
  end

  def destroy
   @site = Site.find(params[:site_id])
   @note = @site.notes.find(params[:id])
   @note.destroy
   redirect_to site_path(@site)
 end


  private
  def note_params
    params.require(:note).permit(:body)
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  def index
    @organisations = Organisation.all
  end

  def show
    @organisation = Organisation.find(params[:id])
  end

  def new
    @organisation = Organisation.new
  end

  def edit
    @organisation = Organisation.find(params[:id])
  end

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      redirect_to @organisation
    else
      flash[:Error] = "Please complete all fields"
      render 'new'
    end
  end

  def update
      @organisation = Organisation.find(params[:id])

      if @organisation.update(organisation_params)
        redirect_to @organisation
      else
        flash[:Error] = "Fail"
        render 'edit'
      end
  end

  def destroy
      @organisation = Organisation.find(params[:id])
      @organisation.destroy
      flash[:success] = "Organisation deleted"
      redirect_to organisations_path
  end

  private
  def organisation_params
    params.require(:organisation).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def create
    @plan = Plan.new(plan_params)

    if @plan.save
      redirect_to @plan
    else
      flash[:Error] = "Please complete all fields"
      render 'new'
    end
  end

  def update
    @plan = Plan.find(params[:id])

    if @plan.update(plan_params)
      redirect_to @plan
    else
      flash[:Error] = "Fail"
      render 'edit'
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:success] = "Plan deleted"
    redirect_to plans_path
  end

  def show
    @plan = Plan.find(params[:id])
  end

  private
  def plan_params
    params.require(:plan).permit(:name, :price)
  end

  def sort_column
    Plan.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
    if params[:search]
      @sites = Site.search(params[:search]).order("created_at DESC")
    end
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site = Site.new(site_params)

    if @site.save
      redirect_to @site
    else
      flash[:Error] = "Please complete all fields"
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:id])

    if @site.update(site_params)
      redirect_to @site
    else
      flash[:Error] = "Fail"
      render 'edit'
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:name, :url, :plan_id, :organisation_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, sort: column, direction: direction
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Site Tracker", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Sites', sites_path %></li>
        <li><%= link_to 'Plans', plans_path %></li>
        <li><%= link_to 'Organisations', organisations_path %></li>
      </ul>
      <!-- form class="navbar-form navbar-left"-->

          <%= form_tag(sites_path, method: "get", id: "search-form", class: "navbar-form navbar-left") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
          <%= submit_tag "Search", class: "btn btn-default" %>
          <% end %>

      <!--/form-->
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
       <li><%= link_to('My account', edit_user_registration_path ) %></li>
       <li><%= link_to('Sign out', destroy_user_session_path, method: :delete ) %></li>
       <% else %>
       <li><%= link_to('Sign in', new_user_session_path) %></li>
       <% end %>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>SiteTracker</title>
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for([@site, @site.notes.build]) do |f| %>
  <div class="form-field">
    <%= f.label :body, 'New note' %> <br>
    <%= f.text_area :body, class: "form-control" %> <br>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= note.created_at.strftime("%d/%m/%Y")%>
  </div>
  <div class="panel-body">
    <%= note.body %>
    <p> <%= link_to "delete", [note.site, note], data: {confirm: "Are you sure?"}, method: :delete %> </p>
  </div>
</div>

app/views/notes/show.html.erb
<%= @note.body %>
<%= link_to "delete", @note_path, data: {confirm: "Are you sure?"}, method: :delete %>

app/views/organisations/_form.html.erb
<%= form_for @organisation do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/organisations/edit.html.erb
<h1>Edit Organisation</h1>
<%= render 'form' %>
<%= link_to "delete", organisation_path, data: {confirm: "Are you sure?"}, method: :delete %>

app/views/organisations/index.html.erb
<h1>Organisations</h1>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <th>Organisation</th>
    </tr>
    <tr>
    <% @organisations.each do |org| %>
      <td><%= link_to org.name, organisation_path(org) %> (<%=org.sites.count%>)</td>
      <td><%= link_to 'Edit', edit_organisation_path(org) %></td>
    </tr>
    <% end %>
  </table>
</div>

<%= link_to 'New Organisation', new_organisation_path, class: "btn btn-primary"  %>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>
<%= render 'form' %>

app/views/organisations/show.html.erb
<h1><%= @organisation.name %></h1>

<div class="jumbotron">
  <p><%= link_to 'Edit organisation', edit_organisation_path %></p>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Sites</div>
  <table class="table">
    <tr>
      <th>URL</th>
      <th>Plan</th>
      <th>Price</th>
    </tr>
    <% monthly_revenue = 0 %>
    <% @organisation.sites.each do |site| %>
    <tr>
      <td><%= link_to site.url, site_path(site) %></td>
      <td><%= site.plan.name %></td>
      <td><%= site.plan.price %></td>
      <td><%= link_to 'Show', site_path(site) %></td>
      <td><%= link_to 'Edit', edit_site_path(site) %></td>
    </tr>
    <% monthly_revenue += site.plan.price %>
    <% end %>
  </table>
</div>
<p><strong>Monthly revenue: </strong>£<%= monthly_revenue %></p>

<p><%= link_to 'New Site', new_site_path, class: "btn btn-primary" %></p>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This application was developed by Andy Pearson.</p>

app/views/pages/home.html.erb
<h1>Welcome to Site Tracker</h1>
<p>This application allows you to manage all of the websites for which you provide support.</p>
<p><%= link_to('View all sites', sites_path) %></p>
<p><%= link_to('View all plans', plans_path) %></p>

app/views/plans/_form.html.erb
<%= form_for @plan do |f| %>
  <% if @plan.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@plan.errors.count, "error") %> prohibited
         this plan from being saved:
       </h2>
       <ul>
         <% @plan.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Edit Plan</h1>
<%= render 'form' %>
<%= link_to "delete", plan_path, data: {confirm: "Are you sure?"}, method: :delete %>

app/views/plans/index.html.erb
<h1>Plans</h1>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <th>Plan</th>
      <th>Price</th>
    </tr>

    <% @plans.each do |p| %>
    <tr>
      <td><%= link_to p.name, plan_path(p) %> (<%= p.sites.count %>)</td>
      <td><%= p.price %></td>
      <td><%= link_to 'Edit', edit_plan_path(p) %></td>
    </tr>
    <% end %>
  </table>
</div>

<%= link_to 'New Plan', new_plan_path, class: "btn btn-primary"  %>

app/views/plans/new.html.erb
<h1>New Plan</h1>
<%= render 'form' %>

app/views/plans/show.html.erb
<h1> Plans > <%= @plan.name %> </h1>

<div class="jumbotron">
  <p>
    <strong>Price:</strong>
    £<%= @plan.price %>
  </p>
  <p><%= link_to 'Edit', edit_plan_path %></p>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Sites</div>
  <table class="table">
    <tr>
      <th>URL</th>
      <th>Organisation</th>
    </tr>

    <% monthly_revenue = 0 %>
    <% @plan.sites.each do |site| %>
    <tr>
      <td><%= link_to site.url, site_path(site) %></td>
      <td><%= site.organisation.name %></td>
      <td><%= link_to 'Edit', edit_site_path(site) %></td>
    </tr>
    <% monthly_revenue += site.plan.price %>
    <% end %>
  </table>
</div>

<p><strong>Monthly revenue: </strong>£<%= monthly_revenue %></p>

app/views/sites/_form.html.erb
<% @site.tags.build %>
<%= form_for @site do |f| %>

  <% if @site.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@site.errors.count, "error") %> prohibited
         this site from being saved:
       </h2>
       <ul>
         <% @site.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <div class="form-group">
     <%= f.label :organisation_id %><br>
     <%= f.collection_select :organisation_id, Organisation.all, :id, :name, class: "form-control" %>
     <%= link_to 'Add organisation', new_organisation_path %>
   </div>

  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cms %><br>
    <%= f.select :cms, ['Drupal 7', 'Drupal 6', 'Wordpress', 'No CMS'], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :plan_id %><br>
    <%= f.collection_select :plan_id, Plan.all, :id, :name, class: "form-control" %>
  </div>

  <h2>Tags</h2>
  <%= render  :partial => 'tags/form', :locals => {:form => f} %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sites/_table.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Sites</div>

  <table class="table">
    <tr>
      <th>URL</th>
      <th>Organisation</th>
      <th>Plan</th>
    </tr>

    <% monthly_revenue = 0 %>
    <% @sites.each do |site| %>
    <tr>
      <td><%= link_to site.url, site_path(site) %></td>
      <td><%= site.organisation.name %></td>
      <td><%= site.plan.name %></td>
      <td><%= link_to 'Edit', edit_site_path(site) %></td>
    </tr>
    <% monthly_revenue += site.plan.price %>
    <% end %>
  </table>
</div>

app/views/sites/edit.html.erb
<h1>Edit Site</h1>
<%= render 'form' %>
<p><%= link_to 'Delete', site_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<div class="jumbotron">
  <% monthly_revenue = 0 %>
  <% @sites.each do |site| %>
  <% monthly_revenue += site.plan.price %>
  <% end %>
  <p>You have <strong> <%= Site.count %> </strong> sites generating <strong>£<%= monthly_revenue %></strong> in monthly recurring revenue.</p>
</div>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <th>URL</th>
      <th>Organisation</th>
      <th>Plan</th>
    </tr>

    <% monthly_revenue = 0 %>
    <% @sites.each do |site| %>
    <tr>
      <td><%= link_to site.url, site_path(site) %></td>
      <td><%= site.organisation.name %></td>
      <td><%= site.plan.name %></td>
      <td><%= link_to 'Edit', edit_site_path(site) %></td>
    </tr>
    <% monthly_revenue += site.plan.price %>
    <% end %>
  </table>
</div>

<%= link_to 'New Site', new_site_path, class: "btn btn-primary" %>

app/views/sites/new.html.erb
<h1>New Site</h1>
<%= form_for :site, url: sites_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sites/show.html.erb
<h1> Sites > <%= link_to @site.url, URI::HTTP.build(host: @site.url).to_s %>
</h1>

<div class="jumbotron">
  <p>
    <strong>Plan:</strong>
    <%= link_to @site.plan.name, plan_path %>
    (£<%= @site.plan.price %>)
  </p>
  <p>
    <strong>Organisation:</strong>
    <%= link_to @site.organisation.name, organisation_path %>
  </p>
  <p><%= link_to 'Edit', edit_site_path %></p>

  <p>
  <b>Tags: </b><%= @site.tags.map { |t| t.name }.join(", ") %>
  </p>
</div>

<% if @site.notes.count > 0 %>
    <%= render @site.notes %>
  <% end %>
  <%= render "notes/form" %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="form-group">
    <%= tag_form.label :name, 'Tag' %>
    <%= tag_form.text_field :name, class: "form-control" %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
  <div class="field">
    <%= tag_form.label :_destroy, 'Remove:' %>
    <%= tag_form.check_box :_destroy %>
  </div>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>